### ISSUE TITLE
Reshape an array in runtime

### ISSUE THREAD

**Issue by votientu** [dsharlet/array#50]
Hi, 

Is it possible to reshape the array in runtime ?

I think you have more available functions in the code than in the README.md. Is it possible to consider a wiki for the list of functions and performance notes ?

If I understand well, the array is implemented as a normal array in C++ (in the stack) ?

Regards,
Tien Tu

**Comment by dsharlet** [comment]
There are more functions than available in the readme, filed #51 to address this.

> Is it possible to reshape the array in runtime ?

To reshape at runtime, there are a few options:
- [array::reshape](https://github.com/dsharlet/array/blob/bc451578a0594a5d68c9f7432db7166422eeca71/array.h#L2403) is similar to vector::resize (changes the shape, and copies the common elements to the new shape).
- [array::set_shape](https://github.com/dsharlet/array/blob/bc451578a0594a5d68c9f7432db7166422eeca71/array.h#L2425) and [reinterpret_shape](https://github.com/dsharlet/array/blob/bc451578a0594a5d68c9f7432db7166422eeca71/array.h#L2751) are similar to numpy reshaping of arrays.
- [move_reinterpret_shape](https://github.com/dsharlet/array/blob/bc451578a0594a5d68c9f7432db7166422eeca71/array.h#L2771) is similar to reinterpret_shape, but it enables move constructing a new array with different rank.

> If I understand well, the array is implemented as a normal array in C++ (in the stack) ?

By default, arrays use `std::allocator`, which allocates on the heap. However, you can replace the allocator with [auto_allocator](https://github.com/dsharlet/array/blob/bc451578a0594a5d68c9f7432db7166422eeca71/array.h#L2836), which will allocate arrays on the stack (if the array itself is on the stack) instead.
