### ISSUE TITLE
`make` broken on Apple Silicon Macs with Xcode

### ISSUE THREAD

**Issue by jiawen** [dsharlet/array#70]
It complains:

```
$ make
mkdir -p obj/test
c++ -I. -c -o obj/test/algorithm.o test/algorithm.cpp  -O2 -ffast-math -fstrict-aliasing -march=native  -std=c++14 -Wall
clang: error: the clang compiler does not support '-march=native'
make: *** [obj/test/algorithm.o] Error 1
```

This is because Apple Clang bundled with Xcode no longer supports the flag. They want you to [pass something like `-mcpu=apple-a14`](https://stackoverflow.com/questions/65966969/why-does-march-native-not-work-on-apple-m1).

**Comment by dsharlet** [comment]
That's pretty annoying. There's no flag for "target CPUs at most 8 years old of any architecture".

We should probably just remove it and leave it as default. We won't target reasonable baseline assumptions like AVX in the tests, but I guess for most of what the tests are doing, that's fine.
