### ISSUE TITLE
reinterpret_shape doesn't resolve bare shape

### ISSUE THREAD

**Issue by linht122** [dsharlet/array#72]
and results in assertion failure if user provides a bare shape.

**Comment by dsharlet** [comment]
Can you clarify what you mean by "bare shape", and also share the particular shape types?

**Comment by linht122** [comment]
A bare Shape I mean its strides are unknown. It happens when we define the shape directly like this `nda::shape<nda::dense_dim<>, nda::dim<>, nda::dim<>> test_shape({100, 100, 1})`.
