### ISSUE TITLE
const_cast for array_ref<const T>

### ISSUE THREAD

**Issue by jiawen** [dsharlet/array#85]
When doing interop with other libraries (e.g., CoreML's `MLMultiArray`), we occasionally need to turn a `array_ref<const T>` to a `array_ref<T>`, since the consumer wants a `T*` even though it is not written to.

Should we provide one?

**Comment by dsharlet** [comment]
I am not sure what the right thing here is. It's perhaps rare/"bad" enough that just requiring users to do their own one-liner is not that bad:
```
auto const_casted = make_array_ref(const_cast<T*>(const_ref.base()), const_ref.shape());
```
I think the hardest part about adding a helper for this is coming up with a reasonable name. If I had to add it right now, I'd probably call it `reinterpret_const` (or maybe `reinterpret_non_const` since the reverse doesn't need this helper...).

**Comment by jiawen** [comment]
Ha, you're right. We can't call it `const_cast`. In my projects, I use camelCase so `constCast` would work :).

**Comment by jiawen** [comment]
How about unsafe_cast?

**Comment by dsharlet** [comment]
That sounds to me like a cast that ignores the size check in `reinterpret`

**Comment by jiawen** [comment]
How about constant_cast? Just looking for synonyms...

The thesaurus is pretty funny - it reminds me that "constant" means very different things in everyday use!

**Comment by dsharlet** [comment]
I prefer `reinterpret_const` to that, because it seems closer to our existing convention (it's the same as `reinterpret` except it reinterprets `const`-ness, and also closer to C++ conventions (the keyword is `const` not 'constant').

**Comment by jiawen** [comment]
Fair enough. I'm fine with `reinterpret_const`. Shall I add it to `array.h`?

**Comment by dsharlet** [comment]
I already basically made this change and then abandoned it :) But go ahead if you want it. I think we only need it for `array_ref` (because `array` of `const T` doesn't make much sense).
